---
# tasks file for apache
- name: install apache2 & dependencies
  apt:
    name: ["apache2", "python-passlib"]
    state: present

- name: Configure Apache2
  template:
    src: apache.conf.j2
    dest: /etc/apache2/apache.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Apache2

- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: "{ { apache_htdpasswd_path } }"
    name: "{{item.username}}"
    password: "{{item.password}}"
    owner: root
    group: www-data
    mode: 0640
  loop: " {{users}} "

- name: Configure Default App
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites_enabled/000-default.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Apache2
